[package]
name = "nu-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
miette = "3.0.0"
thiserror = "1.0.29"
nu-protocol = { path = "../nu-protocol"}
nu-plugin = { path = "../nu-plugin", optional=true}

[features]
plugin = ["nu-plugin"]
