[package]
name = "nu-command"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-engine = { path = "../nu-engine" }
nu-json = { path = "../nu-json" }
nu-path = { path = "../nu-path" }
nu-protocol = { path = "../nu-protocol" }
nu-table = { path = "../nu-table" }
nu-term-grid = { path = "../nu-term-grid" }
nu-parser = { path = "../nu-parser" }
nu-dataframe = { path = "../nu-dataframe", optional = true }
nu-ansi-term = { path = "../nu-ansi-term" }
trash = { version = "1.3.0", optional = true }
unicode-segmentation = "1.8.0"

# Potential dependencies for extras
csv = "1.1.3"
glob = "0.3.0"
Inflector = "0.11"
thiserror = "1.0.29"
sysinfo = "0.20.4"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.2.1"
chrono-tz = "0.6.0"
terminal_size = "0.1.17"
indexmap = { version="1.7", features=["serde-1"] }
lscolors = { version = "0.8.0", features = ["crossterm"] }
bytesize = "1.1.0"
dialoguer = "0.9.0"
rayon = "1.5.1"
regex = "1.5.4"
titlecase = "1.1.0"
meval = "0.2.0"
serde = { version="1.0.123", features=["derive"] }
serde_yaml = "0.8.16"
serde_urlencoded = "0.7.0"
serde_ini = "0.2.0"
eml-parser = "0.1.0"
toml = "0.5.8"
itertools = "0.10.0"
ical = "0.7.0"
calamine = "0.18.0"
roxmltree = "0.14.0"
rand = "0.8"

[dependencies.polars]
version = "0.17.0"
optional = true
features = ["default", "parquet", "json"]

[features]
trash-support = ["trash"]
plugin = ["nu-parser/plugin"]
custom = ["nu-protocol/custom"]
dataframe = ["custom", "nu-dataframe", "polars"]
